# Generated by Django 4.2.3 on 2023-07-29 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.UUIDField()),
                ('family_size', models.IntegerField()),
                ('reserved_seat', models.CharField(max_length=100)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_app.cabin')),
            ],
        ),
    ]
