# Generated by Django 4.2.3 on 2023-08-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatreservation',
            old_name='family_size',
            new_name='fare',
        ),
        migrations.RenameField(
            model_name='seatreservation',
            old_name='cabin',
            new_name='selected_cabin',
        ),
    ]
